examples: Add missing _helpers.py type hints
_helpers.py:42: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
_helpers.py:184: error: Function is missing a return type annotation  [no-untyped-def]