service: Fix mypy errors with types-protobuf 4.24 (#362)
* Update poetry.lock

* service: Fix mypy errors with types-protobuf 4.24

ni_measurementlink_service\measurement\service.py:438: error: Item "_EnumTypeWrapper[Any]" of "Union[type[Enum], _EnumTypeWrapper[Any]]" has no attribute "__iter__" (not iterable)  [union-attr]
ni_measurementlink_service\measurement\service.py:440: error: Item "_EnumTypeWrapper[Any]" of "Union[type[Enum], _EnumTypeWrapper[Any]]" has no attribute "__iter__" (not iterable)  [union-attr]

`EnumTypeWrapper` is not a subclass of `type`, but types-protobuf 4.24
now pretends that `_EnumTypeWrapper[_V]` inherits from `type`:
https://www.github.com/python/typeshed/pull/10203

This affected the type narrowing in `_enum_to_annotations_value`.
`isinstance(enum_type, type)` previously rejected `EnumTypeWrapper`, but
now it accepts `EnumTypeWrapper` (when type checking, it is a subclass of
`_EnumTypeWrapper[_V]`).

* service: Use TypeGuard to simplify type narrowing

Change the return value of _is_protobuf_enum() to TypeGuard[_EnumTypeWrapper]
so that mypy can use this function for type narrowing.

* service: Avoid importing typing_extensions at run time