service: Add missing type hints and use __all__ to explicitly re-export names (#327)
* service: Add missing type hints

Identified with `pyright --verifytypes ni_measurementlink_service`

Signed-off-by: Brad Keryan <brad.keryan@ni.com>

* service: Use __all__ to declare re-exported names

This tells tools like flake8, mypy, and pyright that the re-export is
part of the public API.

Some pyright errors:
measurement.py:30:28 - error: "MeasurementService" is not exported from module "ni_measurementlink_service" (reportPrivateImportUsage)
measurement.py:51:10 - error: "DataType" is not exported from module "ni_measurementlink_service" (reportPrivateImportUsage)
teststand_fixture.py:43:42 - error: "session_management" is not exported from module "ni_measurementlink_service" (reportPrivateImportUsage)

Signed-off-by: Brad Keryan <brad.keryan@ni.com>

* service: Use more specific return type for __exit__

mypy errors:

ni_measurementlink_service/session_management.py:188: error: "bool" is invalid as return type for "__exit__" that always returns False  [exit-return]
ni_measurementlink_service/session_management.py:188: note: Use "typing_extensions.Literal[False]" as the return type or change it to "None"
ni_measurementlink_service/session_management.py:188: note: If return type of "__exit__" implies that it may return True, the context manager may swallow exceptions

Signed-off-by: Brad Keryan <brad.keryan@ni.com>

---------

Signed-off-by: Brad Keryan <brad.keryan@ni.com>