[releases/1.1] Publish_NIMS workflow: Allow updating published releases (#330) (#434)
Publish_NIMS workflow: Allow updating published releases (#330)

When I published 1.1.0, ncipollo/release-action@v1 failed with this error:
```
Error: Error undefined: Tried to update "MeasurementLink Support for Python v1.1.0" which is neither a draft or prerelease. (updateOnlyUnreleased is on)
```

The `Publish_NIMS.yml` workflow doesn't start until you click the
*Publish* button, at which
point the release is no longer a draft.

Signed-off-by: Brad Keryan <brad.keryan@ni.com>
(cherry picked from commit 2a5fb2eaf64587c2b0a6a343a736281e012189df)