workflows: Check documentation in `check_nims` and fix Sphinx errors/warnings (#384)
* workflows: Check documentation

* workflows: Install --with docs

* workflows: Check sphinx-built exit code

* workflows: Tell Sphinx to convert warnings to errors

* service: Fix docstring formatting

* pyproject.toml: Upgrade doc dependencies

* Update poetry.lock

* docs: Suppress cross-reference warnings (due to aliases)

* service: Split up NamedTuple docstrings

Both the "Attributes:" section and autoapi are generating documentation for NamedTuple fields, which leads to warnings like this:

WARNING: duplicate object description of ni_measurementlink_service._internal.parameter.metadata.ParameterMetadata.display_name, other instance in autoapi/ni_measurementlink_service/_internal/parameter/metadata/index, use :noindex: for one of them

* service: Fix Sphinx "unexpected indent" errors

ERROR: Unexpected indentation.
WARNING: Block quote ends without a blank line; unexpected unindent.

* service: Fix argument indentation and some cross-references

* service: Fix lint warnings

* service: Fix some cross-references

* docs: Fix lint warnings