[releases/1.1] examples: Disallow click version 8.1.4 (#326)
examples: Disallow click version 8.1.4 (#325)

It causes mypy errors:

_helpers.py:209: error: Argument 1 has incompatible type "F"; expected <nothing>  [arg-type]
_helpers.py:214: error: Need type annotation for "use_grpc_device_option"  [var-annotated]
_helpers.py:220: error: Need type annotation for "grpc_device_address_option"  [var-annotated]

Signed-off-by: Brad Keryan <brad.keryan@ni.com>
(cherry picked from commit 8789cb36b16d1de2f0268a2afff07fe4d234b01b)