examples: Update VISA examples to use the new session management API (#446)
* examples: Add more instrument IDs to _visa_dmm.py

RuntimeError: The ID query failed. This may mean that you selected the wrong instrument, your instrument did not respond, or you are using a model that is not officially supported by this driver. Instrument ID: National Instruments,Instrument Simulator,0181CCEE,2.0.1.d1

* examples: Update nivisa_dmm_measurement to use the new session management API

* examples: Update output_voltage_measurement to use the new session management API

* examples: Ignore missing type stubs for decouple

* examples: Simplify `with` block

* .env: Add MEASUREMENT_VISA_DMM_SIMULATE