generator: Add missing type hints
ni_measurementlink_generator\template.py:14: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
ni_measurementlink_generator\template.py:27: error: Function is missing a return type annotation  [no-untyped-def]
ni_measurementlink_generator\template.py:27: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]