mypy: Disallow untyped defs (#379)
* service: Fix grpc_servicer type hints

ni_measurementlink_service\_internal\grpc_servicer.py:168: error: Function is missing a return type annotation  [no-untyped-def]
ni_measurementlink_service\_internal\grpc_servicer.py:311: error: Function is missing a return type annotation  [no-untyped-def]

* service: Fix a serializer type hint

ni_measurementlink_service\_internal\parameter\serializer.py:113: error: Function is missing a return type annotation  [no-untyped-def]

* service: Add a missing cast

* service: More grpc_servicer type hints

* service: More type hints

* pyproject.toml: Enable mypy --disable-untyped-defs

* generator: Add missing type hints

ni_measurementlink_generator\template.py:14: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
ni_measurementlink_generator\template.py:27: error: Function is missing a return type annotation  [no-untyped-def]
ni_measurementlink_generator\template.py:27: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]

* generator: Disallow untyped defs

* examples: Add missing _helpers.py type hints

_helpers.py:42: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
_helpers.py:184: error: Function is missing a return type annotation  [no-untyped-def]

* examples: Enable mypy --disallow-untyped-defs and fix errors

* tests: Allow untyped defs :(

* generator: Fix lint errors

* generator: Fix test errors caused by rerunning black

* examples: Only type alias outputs when needed for yield + return